### ISSUE TITLE
test of A02 - AUSTEN CCT.ifc 

### ISSUE THREAD

**Issue by cubalibre** [tomvandig/web-ifc-three#1]
I downloaded to test the ifc  Sam Romeo file . I tried to upload it locally. If I load it from the js folder it works. If I load it from the jsm folder, nothing is seen. What should I do to see the js console from Chrome? .... I always right click on browser page and then inspect ... but in this case the right click doesn't work

**Comment by agviegas** [comment]
Hello there! You can open the Chrome Developer Tools with F12. 
I have downloaded the library using the zip download and I am able to load IFC files from both versions (js and jsm). Are you using the last version of the library? Is that problem happening only in that IFC or in all IFC files?

**Comment by cubalibre** [comment]
Hi Antonio,
I use the **last version of the library** and I have this error in jsm and **only in that IFC** file.
I report the javascript console error:
bundle.js:569 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ bundle.js:569
bundle.js:570 falling back to ArrayBuffer instantiation
(anonymous) @ bundle.js:570
bundle.js:4691 Wrote file
bundle.js:840 Loading: example.ifc
bundle.js:840 Read 
bundle.js:840 Loading 
bundle.js:840 Tape 6691830
bundle.js:840 Lines normal 139332
bundle.js:840 Max express ID 139331
bundle.js:840 Loaded 139332 lines in 133 ms!
bundle.js:840 Unexpected style type: 846575682 at 3216
bundle.js:37757 RuntimeError: memory access out of bounds
    at <anonymous>:wasm-function[137]:0x10433
    at <anonymous>:wasm-function[137]:0x10862
    at <anonymous>:wasm-function[137]:0x10614
    at <anonymous>:wasm-function[121]:0x7537
    at <anonymous>:wasm-function[121]:0x9e5b
    at <anonymous>:wasm-function[121]:0x9afd
    at <anonymous>:wasm-function[121]:0x83f4
    at <anonymous>:wasm-function[440]:0x31301
    at <anonymous>:wasm-function[444]:0x316e7
    at Object.LoadAllGeometry (eval at new_ (http://localhost/ifc7/examples/jsm/bundle.js:3641:27), <anonymous>:8:10)
(anonymous) @ bundle.js:37757

I am casak of Albisola(Italy) cubalibre is my old account on github ;-)

**Comment by agviegas** [comment]
I see. Can you please send me a link to that file? Right now I don't know what file you are referring to. Thanks!

**Comment by cubalibre** [comment]
www.solserver.it/casak/A02%20-%20AUSTEN%20CCT.ifc

**Comment by agviegas** [comment]
It is strange, as I am able to load the model. I am working with the last version. What version of web-ifc are you using?
![image](https://user-images.githubusercontent.com/56475338/111532379-e2b6a780-8765-11eb-9308-703313dbf35e.png)

**Comment by cubalibre** [comment]
i downloaded the latest version and now it works. Thank you.
