### ISSUE TITLE
Code comments 

### ISSUE THREAD

**Issue by cubalibre** [tomvandig/web-ifc-three#2]
Hello there! This library is opensource. Ok. Even if a well-written code does not need comments, it would be very useful for me to find comments. On the contrary, these comments seem to be very few. I would like to understand and also learn, through an example like this, the best js programming techniques. For this I ask you if it is possible to add other comments to the code in the open source spirit, aimed at everyone. Thanks for your time.

**Comment by agviegas** [comment]
We are currently writing documentation for the library; this should help users understand how it works. However:

1. To use the library you don't need to understand how it works internally. This library is the official Three.js IFC Loader, and can be used like any other Loader. You can look at the official [Three.js example](https://threejs.org/examples/#webgl_loader_ifc) to see how it works, as well as its official documentation. 

2. I don't think adding comments is a good idea, as they are a [code smell](https://refactoring.guru/smells/comments). Comments should only be for users interested in helping us maintain and improve the library, and right now we don't need them. Unfortunately, we also don't have the time to comment the whole library right now.
