### ISSUE TITLE
Test ifc file: color noise when rotating the object

### ISSUE THREAD

**Issue by cubalibre** [tomvandig/web-ifc-three#3]
https://drive.google.com/file/d/1cjq3dDVDpq17PkMvO7vtp4k9ZVW-qGVA/view?usp=sharing

**Comment by agviegas** [comment]
Without a description, we cannot help you on this issue. It seems to me that when you say "colour noise" you are referring to Z fighting by overlapping surfaces. This is not a problem of the library, but that the IFC model has overlapping surfaces.
