### ISSUE TITLE
indexed buffer geometry

### ISSUE THREAD

**Issue by antoniohof** [tomvandig/web-ifc-three#6]
Hi there,

I saw you made the viewer more optimized by merging the model into a single geometry. really nice!

I have a problem now, I wonder how to enable/disable single parts of the model with this approach.

I saw its possible if the buffer geometry is indexed and then you can pass a drawRange to the it, so it draws only what you want.

Do any of you maybe have a direction I could pursue, or maybe its not possible? I should go back to working with simple geometries if I want to manipulate the model?

Thank you,

Antonio

**Comment by agviegas** [comment]
Hey, sorry, I just saw this. With the last changes you should be able to pick and hide parts of the model, as well as getting properties for objects! If you specifically want to hide objects that are far away, we could do something with shaders. What do you mean by "manipulation"? 

Let us know if you have any questions or suggestions regarding this. We will keep improving this in future versions.
